FROM python:3.10-slim

WORKDIR /app

COPY backend/ /app/
COPY yolov8_weights/ /app/yolov8_weights/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
